#!/bin/bash

## utils

. bin/autoload

## Apps used on System

## Update System

Warning "Adding PPAs"

. bin/system-settings/add-repositoryes

Warning "Updating System"

UpdateSystem

## Essential packages

Warning "Install essentials"

Install "build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext p7zip p7zip-full p7zip-rar lzma lzma-dev ubuntu-restricted-extras"

## Git + Git-Cola + Node + NVM + VIM + Meld

Warning "Dev essentials"

Install "git git-cola vim meld"

Warning "Install and Configure NVM and NodeJS (stable and 0.12)"

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

mkdir ~/.nvm
nvm install stable
nvm install 0.12

Warning "Install Heroku toolbelt"

wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

Warning "Copy configs to /home"

cp -v bin/system-settings/.bashrc bin/system-settings/.gitconfig bin/system-settings/.vimrc $HOME

## Others

Warning "Install others"

Install "gimp inkscape vlc browser-plugin-vlc"

## Optimize Ubuntu

Warning "Optimize Ubuntu"

Install "ubuntu-tweak compizconfig-settings-manager preload indicator-keylock"

## Optimize battery management

Warning "Optimize battery management"

sudo apt-get remove laptop-mode-tools

Install "tlp tlp-rdw"

sudo tlp start

## Remember

Alert "Remember to install later: " "Chrome\n- Slack\n- Java (uurgh)"
