#!/bin/bash

## utils

. bin/autoload

## Apps used on System

## Update System

Warning "Adding PPAs"

. bin/system-settings/add-repositoryes

Warning "Updating System"

UpdateSystem

## Essential packages

Warning "Install essentials"

Install "build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext p7zip p7zip-full p7zip-rar lzma lzma-dev ubuntu-restricted-extras apt-transport-https ca-certificates software-properties-common terminator gnupg snapd advancecomp jhead jpegoptim libjpeg-turbo-progs optipng"

## Dev essentials

Warning "Dev essentials"

Install "git vim zsh"

## Vundle (VIM Package Manager)

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

## Copy configs to home

cp -v bin/system-settings/.bashrc bin/system-settings/.gitconfig bin/system-settings/.vimrc $HOME

## Install NVM

Warning "Install and Configure NVM and NodeJS (stable and 0.12)"

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

mkdir ~/.nvm
nvm install stable
nvm install 0.12
nvm use stable
npm install svgo -g

## Install RVM

sudo apt-get install rvm

## Install Docker

sudo apt-get install docker-ce
sudo groupadd docker
sudo usermod -aG docker $USER

## Utils

Warning "Install utils"

Install "gimp inkscape vlc browser-plugin-vlc shutter unetbootin shotwell"

## Video utils

Warning "Install video utils"

Install "ffmpeg mint-meta-codecs pitivi kdenlive obs-studio audacity simplescreenrecorder"

## Optimize Ubuntu

Warning "Optimize Ubuntu"

Install "ubuntu-tweak compizconfig-settings-manager preload indicator-keylock gir1.2-gtop-2.0"

## Optimize battery management

Warning "Optimize battery management"

sudo apt-get remove laptop-mode-tools

Install "tlp tlp-rdw"

sudo tlp start

## Install Spotify
sudo snap install spotify

## Install Java

sudo apt-get install oracle-java8-installer

## Remember

Alert 
    "
    ############################## \n \n
    Remember to install later: \n
        - Chrome \n
        - Slack \n
    You need logout to make changes in RVM \n
    And look this link to run RVM on all Terminals: \n
    https://github.com/rvm/ubuntu_rvm#2-change-your-terminal-window"
