#!/bin/bash

RED='\033[0;31m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color

## Apps used on System

## Update System

printf "${RED}Updating System${NC}\n------- \n"

sudo apt-get update && sudo apt-get upgrade -y

## Essential packages

printf "${RED}Install essentials${NC}\n------- \n"

sudo apt-get install -y build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext p7zip p7zip-full p7zip-rar lzma lzma-dev ubuntu-restricted-extras

## Git + Git-Cola + Node + NVM + VIM

printf "${RED}Dev essentials${NC}\n------- \n"

sudo apt-get install -y git git-cola nodejs vim

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

. ~/.nvm/nvm.sh

nvm install stable
nvm install 0.12

## Others

printf "${RED}Install others${NC}\n------- \n"

sudo add-apt-repository ppa:indicator-multiload/stable-daily
sudo add-apt-repository ppa:transmissionbt/ppa

sudo apt-get update

sudo apt-get install -y gimp inkscape indicator-multiload transmission transmission-qt vlc browser-plugin-vlc 

## Remember

printf "\n ---- \n\n${NC}Remember to install later: \n${BLUE}- SublimeText\n- Chrome\n- Slack\n- Java (uurgh)\n- Meld${NC}\n\n ---- \n"
