#!/bin/bash

## utils

. bin/colors
. bin/messages
. bin/utils

## Apps used on System

## Update System

Warning "Adding PPAs"

. bin/repositoryes

Warning "Updating System"

UpdateSystem

## Essential packages

Warning "Install essentials"

Install "build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext p7zip p7zip-full p7zip-rar lzma lzma-dev ubuntu-restricted-extras"

## Git + Git-Cola + Node + NVM + VIM + Meld

Warning "Dev essentials"

Install "git git-cola nodejs vim meld"

Warning "Install and Configure NVM"

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

mkdir ~/.nvm
nvm install stable
nvm install 0.12

Warning "Install Heroku toolbelt"

wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

Warning "Copy configs to /home"

cp -v .bashrc .gitconfig .nvmrc .vimrc $HOME

## Others

Warning "Install others"

Install "gimp inkscape vlc browser-plugin-vlc"

## Optimize Ubuntu

Warning "Optimize Ubuntu"

Install "indicator-multiload synapse ubuntu-tweak compizconfig-settings-manager preload zramswap-enabler indicator-keylock"

## Optimize battery management

Warning "Optimize battery management"

sudo apt-get remove laptop-mode-tools

Install "tlp tlp-rdw"

sudo tlp start

## Remember

Alert "Remember to install later: " "- SublimeText\n- Chrome\n- Slack\n- Java (uurgh)"
